name: SuddenDeath
version: 2.0.8
main: org.nguyendevs.suddendeath.SuddenDeath
softdepend: [WorldGuard]
api-version: 1.19
commands:
  sdstatus:
    description: Shows your current status (bleeding, ...).
    aliases: [sds, suddendeath]
  sdmob:
    description: Main command from the custom monster system.
    aliases: [sdm, sdmonster]
permissions:
  suddendeath.status:
    default: op
  suddendeath.op:
    default: op
  suddendeath.update-notify:
    default: op
  suddendeath.difficulty.*:
    default: op
    children:
      suddendeath.difficulty.sandbox: true
      suddendeath.difficulty.difficult: true
      suddendeath.difficulty.hardcore: true
      suddendeath.difficulty.death-wish: true
      suddendeath.difficulty.sudden-death: true