name: SuddenDeath
version: 2.2.4
main: org.nguyendevs.suddendeath.SuddenDeath
softdepend: [WorldGuard, ProtocolLib]
api-version: 1.19
commands:
  sds:
    description: Shows your current status (bleeding, ...).
    aliases: [sds, suddendeath]
  sdm:
    description: Main command from the custom monster system.
    aliases: [sdmob, sdmonster]
permissions:
  suddendeath.status:
    default: true
  suddendeath.admin:
    default: op
  suddendeath.update-notify:
    default: op
  suddendeath.recipe:
    default: true