name: SuddenDeath
version: 2.2.2
main: org.nguyendevs.suddendeath.SuddenDeath
softdepend: [WorldGuard, ProtocolLib]
api-version: 1.19
commands:
  sdstatus:
    description: Shows your current status (bleeding, ...).
    aliases: [sds, suddendeath]
  sdmob:
    description: Main command from the custom monster system.
    aliases: [sdm, sdmonster]
permissions:
  suddendeath.status:
    default: true
  suddendeath.admin:
    default: op
  suddendeath.update-notify:
    default: op
  suddendeath.recipe:
    default: true